### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by CarloRamponi** [mikex86/LibreCuda#13]
When I try to use a global (on-device) variable in a kernel function, kernel execution fails (I believe), and the process hangs on stream await.

**This code works:**
```c
__device__ int global_int = 2;

extern "C" __global__ void write_float_sum(float *dst, short a, float b) {
    *dst = (a + b);
}
```

**This code doesn't:**
```c
__device__ int global_int = 2;

extern "C" __global__ void write_float_sum(float *dst, short a, float b) {
    *dst = (a + b + global_int);
}
```

```
$ ./LibreCuda
Device count: 1
Num functions: 1
  function "write_float_sum"
A value: 314
B value: 0.31415
Dst value (pre exec): 0.00000
// HANGS HERE
```

Both kernels were compiled with this command:
```
nvcc -std=c++11 -arch sm_80 write_float.cu -o write_float.cubin --cubin
```

**Comment by mikex86** [comment]
Global variables were not handled correctly because:

1. constant bank 4 which is where the globals live in this example was not even referenced in the qmd launch command due to the constant not refering to a function. Introduced a null function, whose constants are appended to all functions.
2. alignment failure of sections to 128. Added logic to rebuild the image align to 128 and adjust section addresses.
