### ISSUE TITLE
[NOTE] Gdev

### ISSUE THREAD

**Issue by TheFloatingBrain** [mikex86/LibreCuda#19]
I hope I'm not too much of a nuisance if I pass along a link to [GDev](https://github.com/CPFL/gdev) `First-Class GPU Resource Management: Device Drivers, Runtimes, and CUDA Compilers for Nouveau` (and a [conference paper](https://www.usenix.org/system/files/conference/atc12/atc12-final319.pdf)). This looks like a great project, I don't know what happened too it or why it did not go forward. I would really like to see a Libre CUDA driver that is maintained, y'all do great work!

**Comment by mikex86** [comment]
The goal of this repository seems very similar to what LibreCUDA is trying to achieve. However, the tools ptx2sass and sass2cubin are probably pretty much unusable by now due to nvidia isa changes. LibreCUDA will eventually try to replace them as well. Currently you still need ptxas for codegen when using LibreCUDA.

**Comment by TheFloatingBrain** [comment]
I figured you may well be aware of the project, I came across it and figured I would pass it along in case you might be able to use code/study it, its curious to me that a working CUDA driver failed :shrug: .

Thanks for taking the time to reply :)
